name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  get-template:
    runs-on: ubuntu-latest

    steps:
      - name: Download
        run: wget https://raw.githubusercontent.com/zhangtianli2006/LabUI/main/test-template.zip

      - name: Unzip
        run:
          unzip test-template.zip

  install:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: npm i svelte-preprocess node-sass

      - name: Install LabUI
        run: npm i @zhangtianli2006/lab-ui

      - name: NPM Install
        run:
          npm i

      - name: Build
        run:
          npm run build
