name: Test NPM

on:
  push:
    branches: [ "main" ]

jobs:
  test-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Download
        run: wget https://raw.githubusercontent.com/ZTL-UwU/LabUI/main/test-template.zip

      - name: Unzip
        run: unzip test-template.zip

      - name: Install Dependencies
        run: npm i --save svelte-preprocess node-sass

      - name: Install LabUI
        run: npm i --save @ztl-uwu/labui

      - name: NPM Install
        run: npm i

      - name: Build
        run: npm run build
